dongles:
  - name: PD_Main
    host: 127.0.0.1
    port: 1234
    gain: 30
    channels:
      - name: PD
        frequency: 158.9925e6
        tone_type: DPL
        tone_value: 223
        squelch: -40
        sink: pd_sink

  - name: FD_Main
    host: 127.0.0.1
    port: 1235
    gain: 35
    channels:
      - name: FD_UHF
        frequency: 483.725e6
        tone_type: DPL
        tone_value: 047
        sink: fd_sink
      - name: FD_Lowband
        frequency: 46.22e6
        tone_type: PL
        tone_value: 123.0
        sink: fd_sink
